use std::env;
use std::path::PathBuf;
use std::process::Command;

const MANIFEST_PATH: &str = "../../data/app-variants.json";
const SCHEMA_PATH: &str = "../../data/io.github.majamato.Houra.gschema.xml";
const PREPARE_DEV: &str = "../../scripts/prepare-dev.py";

fn manifest_string(manifest: &serde_json::Value, variant: &str, key: &str) -> String {
    manifest
        .get(variant)
        .and_then(|variant| variant.get(key))
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| panic!("{MANIFEST_PATH} is missing {variant}.{key}"))
        .to_owned()
}

fn manifest_bool(manifest: &serde_json::Value, variant: &str, key: &str) -> bool {
    manifest
        .get(variant)
        .and_then(|variant| variant.get(key))
        .and_then(serde_json::Value::as_bool)
        .unwrap_or_else(|| panic!("{MANIFEST_PATH} is missing {variant}.{key}"))
}

fn main() {
    println!("cargo:rerun-if-changed={MANIFEST_PATH}");
    println!("cargo:rerun-if-changed=../../data/io.github.majamato.Houra.gresource.xml");
    println!("cargo:rerun-if-changed=../../data/ui/window.ui");
    println!("cargo:rerun-if-changed=../../data/ui/week-day-cell.ui");
    println!("cargo:rerun-if-changed=../../data/ui/entry-row.ui");
    println!("cargo:rerun-if-changed=../../data/ui/management-row.ui");
    let manifest = std::fs::read_to_string(MANIFEST_PATH)
        .unwrap_or_else(|error| panic!("could not read {MANIFEST_PATH}: {error}"));
    let manifest: serde_json::Value = serde_json::from_str(&manifest)
        .unwrap_or_else(|error| panic!("could not parse {MANIFEST_PATH}: {error}"));
    let variant = if env::var_os("CARGO_FEATURE_DEV_APP").is_some() {
        "devel"
    } else {
        "stable"
    };
    let out_dir = env::var_os("OUT_DIR").map(PathBuf::from);
    let Some(out_dir) = out_dir else {
        panic!("Cargo did not provide OUT_DIR");
    };
    // Debug formatting emits properly escaped Rust string literals.
    let identity = format!(
        "// Build-selected application identity. Generated by `build.rs`; do not edit.\n\
         /// The selected application variant: `\"stable\"` or `\"devel\"`.\n\
         pub const APP_VARIANT: &str = {variant:?};\n\
         /// Reverse-DNS application ID shared by GApplication, the desktop\n\
         /// file, icons, GSettings, notifications, and package metadata.\n\
         pub const APP_ID: &str = {:?};\n\
         /// User-visible application name.\n\
         pub const APP_NAME: &str = {:?};\n\
         /// Data directory holding this variant's database.\n\
         pub const DATA_SUBDIR: &str = {:?};\n\
         /// GSettings path holding this variant's preferences.\n\
         pub const SETTINGS_PATH: &str = {:?};\n\
         /// UUID of this variant's GNOME Shell extension.\n\
         pub const EXTENSION_UUID: &str = {:?};\n\
         /// Whether a fresh install starts with the desktop session.\n\
         pub const DEFAULT_LAUNCH_AT_LOGIN: bool = {};\n",
        manifest_string(&manifest, variant, "app_id"),
        manifest_string(&manifest, variant, "app_name"),
        manifest_string(&manifest, variant, "data_subdir"),
        manifest_string(&manifest, variant, "settings_path"),
        manifest_string(&manifest, variant, "extension_uuid"),
        manifest_bool(&manifest, variant, "launch_at_login_default"),
    );
    std::fs::write(out_dir.join("app_identity.rs"), identity)
        .unwrap_or_else(|error| panic!("could not write app_identity.rs: {error}"));
    if env::var_os("CARGO_FEATURE_NATIVE_UI").is_none() {
        return;
    }
    if env::var_os("CARGO_FEATURE_DEV_APP").is_some() {
        println!("cargo:rerun-if-changed={PREPARE_DEV}");
        println!("cargo:rerun-if-changed={SCHEMA_PATH}");
        let schema_dir = out_dir.join("dev-settings");
        let status = Command::new("python3")
            .arg("-B")
            .arg(PREPARE_DEV)
            .arg("--output-dir")
            .arg(&schema_dir)
            .arg("--schemas-only")
            .status();
        match status {
            Ok(status) if status.success() => {}
            Ok(status) => panic!("{PREPARE_DEV} exited with {status}"),
            Err(error) => panic!("could not start {PREPARE_DEV}: {error}"),
        }
        println!(
            "cargo:rustc-env=HOURA_DEV_SCHEMA_DIR={}",
            schema_dir.display()
        );
    }
    let status = Command::new("glib-compile-resources")
        .arg("--target")
        .arg(out_dir.join("houra.gresource"))
        .arg("--sourcedir")
        .arg("../../data")
        .arg("../../data/io.github.majamato.Houra.gresource.xml")
        .status();
    match status {
        Ok(status) if status.success() => {}
        Ok(status) => panic!("glib-compile-resources exited with {status}"),
        Err(error) => panic!("could not start glib-compile-resources: {error}"),
    }
    let locale_dir = out_dir.join("locale");
    println!("cargo:rerun-if-changed=../../po/LINGUAS");
    let languages = std::fs::read_to_string("../../po/LINGUAS")
        .unwrap_or_else(|error| panic!("could not read po/LINGUAS: {error}"));
    for language in languages
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
    {
        let source = PathBuf::from("../../po").join(format!("{language}.po"));
        println!("cargo:rerun-if-changed={}", source.display());
        let target_dir = locale_dir.join(language).join("LC_MESSAGES");
        std::fs::create_dir_all(&target_dir)
            .unwrap_or_else(|error| panic!("could not create locale output directory: {error}"));
        let status = Command::new("msgfmt")
            .arg("--check")
            .arg("--output-file")
            .arg(target_dir.join("houra.mo"))
            .arg(source)
            .status()
            .unwrap_or_else(|error| panic!("could not start msgfmt: {error}"));
        assert!(status.success(), "msgfmt failed for {language}");
    }
    println!(
        "cargo:rustc-env=HOURA_BUILD_LOCALE_DIR={}",
        locale_dir.display()
    );
}
